# Site
name: "Pat Hannon"
title: "Pat Hannon"
description: "Pastor. Musician. Student of Jesus."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
google_analytics: 
disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  pat:
    name: Pat
    display_name: "Pat Hannon"
    gravatar: 0c95df1b00f88c1b90e3ed8707700b56
    email: 
    web: https://PatHannon.net
    twitter: https://twitter.com/PHannon
    description: Dr. Pat Hannon is a pastor, currently serving at <a href="unity-umc.org">Unity UMC</a>. He is a musician. Listen to his latest music on <a href="youtube.com/PatrickHannonMusic">YouTubeC</a>. Most importantly, he is a life-long student of Jesus.
 
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
